//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.user_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_ownership
    {
        public int id { get; set; }
        public string Plant { get; set; }
        public string Optgroup { get; set; }
        public string Ownership { get; set; }
        public string LocationTree { get; set; }
        public string UserComment { get; set; }
    }
}
