//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.user_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Screens
    {
        public int id { get; set; }
        public int Screen_num { get; set; }
        public string Discription { get; set; }
        public int User_id { get; set; }
        public string ScreenUrl { get; set; }
        public Nullable<System.DateTime> StartDisplayTime { get; set; }
        public Nullable<System.DateTime> StopDisplayTime { get; set; }
        public Nullable<int> ResetRate { get; set; }
        public Nullable<double> ZoomLevel { get; set; }
    
        public virtual users L_users { get; set; }
    }
}
