//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.user_management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GADATAEntitiesUserManagement : DbContext
    {
        public GADATAEntitiesUserManagement()
            : base("name=GADATAEntitiesUserManagement")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userRoles> c_userRoles { get; set; }
        public virtual DbSet<usersPermisions> h_usersPermisions { get; set; }
        public virtual DbSet<users> L_users { get; set; }
        public virtual DbSet<L_Screens> L_Screens { get; set; }
    }
}
