//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.UltraLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_CompletedPlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public h_CompletedPlans()
        {
            this.h_measurementRemarks = new HashSet<h_measurementRemarks>();
        }
    
        public int id { get; set; }
        public string InspectionPlanname { get; set; }
        public Nullable<System.DateTime> planStartDT { get; set; }
        public Nullable<System.DateTime> planEndDT { get; set; }
        public string Inspector { get; set; }
        public string InspectionLaptop { get; set; }
        public Nullable<int> PlanLenght { get; set; }
        public Nullable<int> TotalMeasurements { get; set; }
        public Nullable<int> UniqueMeasurePoints { get; set; }
        public Nullable<int> Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_measurementRemarks> h_measurementRemarks { get; set; }
    }
}
