//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.UltraLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_measurementRemarks
    {
        public int id { get; set; }
        public Nullable<int> CompletedPlans_id { get; set; }
        public string spotname { get; set; }
        public string EvaluationClass { get; set; }
        public string Autocomment { get; set; }
        public string InspectorComment { get; set; }
        public string Partname { get; set; }
        public Nullable<double> measuredThickness { get; set; }
        public Nullable<double> NominalDiameter { get; set; }
        public Nullable<System.DateTime> ULDateTime { get; set; }
        public string InspectionPlanname { get; set; }
        public string InspectionLaptop { get; set; }
        public string Inspector { get; set; }
    
        public virtual h_CompletedPlans h_CompletedPlans { get; set; }
    }
}
