//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.UltraLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_active_info
    {
        public int id { get; set; }
        public string Partname { get; set; }
        public string InspectionPlanname { get; set; }
        public Nullable<int> Planlength { get; set; }
        public Nullable<int> IndexOfTestsequence { get; set; }
        public string Inspector { get; set; }
        public string teststation { get; set; }
        public string InspectionLaptop { get; set; }
        public Nullable<System.DateTime> ULDateTime { get; set; }
        public System.DateTime Heartbeat { get; set; }
    }
}
