//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.UltraLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_UltralogData
    {
        public int id { get; set; }
        public string Spotname { get; set; }
        public string EvaluationClass { get; set; }
        public string Autocomment { get; set; }
        public string InspectorComment { get; set; }
        public string Partname { get; set; }
        public string InspectionPlanname { get; set; }
        public Nullable<double> measuredThickness { get; set; }
        public Nullable<double> NominalDiameter { get; set; }
        public Nullable<System.DateTime> ULDateTime { get; set; }
        public Nullable<int> Planlength { get; set; }
        public Nullable<int> BackWallEchos { get; set; }
        public Nullable<int> FlawEchos { get; set; }
        public Nullable<int> GasporeEchos { get; set; }
        public Nullable<int> IndexOfTestsequence { get; set; }
        public Nullable<int> MinimumIndentation { get; set; }
        public Nullable<double> MinimumIndentationMM { get; set; }
        public string Inspector { get; set; }
        public string teststation { get; set; }
        public string NamePlate1 { get; set; }
        public string MaterialPlate1 { get; set; }
        public Nullable<double> ThicknessPlate1 { get; set; }
        public string NamePlate2 { get; set; }
        public string MaterialPlate2 { get; set; }
        public Nullable<double> ThicknessPlate2 { get; set; }
        public string NamePlate3 { get; set; }
        public string MaterialPlate3 { get; set; }
        public Nullable<double> ThicknessPlate3 { get; set; }
        public string InspectionLaptop { get; set; }
    }
}
