//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.UltraLog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UltraLogEntities : DbContext
    {
        public UltraLogEntities()
            : base("name=UltraLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<h_CompletedPlans> h_CompletedPlans { get; set; }
        public virtual DbSet<h_measurementRemarks> h_measurementRemarks { get; set; }
        public virtual DbSet<rt_active_info> rt_active_info { get; set; }
        public virtual DbSet<rt_UltralogData> rt_UltralogData { get; set; }
        public virtual DbSet<L_InspectionPlans> L_InspectionPlans { get; set; }
    }
}
