//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Alert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerts_Supervisie
    {
        public string Location { get; set; }
        public string logtext { get; set; }
        public Nullable<int> RT { get; set; }
        public Nullable<int> DT { get; set; }
        public string time { get; set; }
        public string Classification { get; set; }
        public string Subgroup { get; set; }
        public string Severity { get; set; }
        public string Logcode { get; set; }
        public string Logtype { get; set; }
        public int refId { get; set; }
        public System.DateTime timestamp { get; set; }
        public string LocationTree { get; set; }
        public Nullable<int> ClassTree { get; set; }
    }
}
