//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Alert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_controller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_controller()
        {
            this.GunCylinderefernce = new HashSet<GunCylinderefernce>();
            this.SBCUrefernce = new HashSet<SBCUrefernce>();
        }
    
        public int id { get; set; }
        public string controller_name { get; set; }
        public string sys_id { get; set; }
        public string location { get; set; }
        public string ipaddress { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<bool> reconnect { get; set; }
        public Nullable<int> log_flag { get; set; }
        public Nullable<int> enable_bit { get; set; }
        public Nullable<int> variable_mask { get; set; }
        public Nullable<int> statement_mask { get; set; }
        public Nullable<int> error_no_log_mask { get; set; }
        public Nullable<bool> alarm_monitor { get; set; }
        public Nullable<int> state_monitor { get; set; }
        public Nullable<int> state_filter { get; set; }
        public Nullable<int> poll_rate { get; set; }
        public Nullable<bool> poll_not_saved { get; set; }
        public Nullable<bool> poll_error_file_list { get; set; }
        public Nullable<bool> poll_action_file_list { get; set; }
        public Nullable<int> read_sys { get; set; }
        public Nullable<int> generation { get; set; }
        public string ownership { get; set; }
        public string Plant { get; set; }
        public string Area { get; set; }
        public string SubArea { get; set; }
        public Nullable<int> event_mask { get; set; }
        public Nullable<int> record_mask { get; set; }
        public Nullable<int> error_trigger_mask { get; set; }
        public Nullable<int> prog_info_ign_mask { get; set; }
        public Nullable<int> production_monitor { get; set; }
        public Nullable<int> poll_clock { get; set; }
        public Nullable<int> rt_flags { get; set; }
        public string description { get; set; }
        public string swversion { get; set; }
        public Nullable<int> keycode { get; set; }
        public Nullable<int> ipcb_flags { get; set; }
        public string LocationTree { get; set; }
        public string Assetnum { get; set; }
        public string ProductionTeam { get; set; }
        public string ResponsiblePloeg { get; set; }
        public string ClassificationTree { get; set; }
        public string CLassificationId { get; set; }
        public Nullable<int> pjv_action_mask { get; set; }
        public Nullable<int> pjv_event_mask { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GunCylinderefernce> GunCylinderefernce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SBCUrefernce> SBCUrefernce { get; set; }
    }
}
