//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Alert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_SMSconfig
    {
        public int id { get; set; }
        public int c_smsSystem_id { get; set; }
        public int c_CPT600_id { get; set; }
    
        public virtual c_CPT600 c_CPT600 { get; set; }
        public virtual c_smsSystem c_smsSystem { get; set; }
    }
}
