//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Alert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GunCylinderefernce
    {
        public Nullable<int> Controller_id { get; set; }
        public Nullable<byte> tool_id { get; set; }
        public Nullable<System.DateTime> SampleStart { get; set; }
        public Nullable<int> nDataPoints { get; set; }
        public Nullable<double> avg { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Stdev { get; set; }
        public Nullable<double> UCL { get; set; }
        public Nullable<double> LCL { get; set; }
        public int id { get; set; }
        public string Variant { get; set; }
        public Nullable<bool> Active { get; set; }
        public byte[] C_timestamp { get; set; }
        public string Comment { get; set; }
    
        public virtual c_controller c_controller { get; set; }
    }
}
