//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Alert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_controlLimits
    {
        public int id { get; set; }
        public int c_trigger_id { get; set; }
        public bool isdead { get; set; }
        public int Createuser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ChangeUser { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<double> UpperLimit { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public string Comment { get; set; }
        public string alarmobject { get; set; }
        public Nullable<int> l_variants_id { get; set; }
    
        public virtual c_triggers c_triggers { get; set; }
        public virtual L_users L_CreateUser { get; set; }
        public virtual L_users L_ChangeUser { get; set; }
        public virtual l_variants l_variants { get; set; }
    }
}
