//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Alert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_dummyControlchartResult
    {
        public int id { get; set; }
        public string alarmobject { get; set; }
        public System.DateTime timestamp { get; set; }
        public double value { get; set; }
        public Nullable<double> UpperLimit { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public Nullable<int> l_controlLimits_id { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<double> OptValue { get; set; }
    
        public virtual l_controlLimits l_controlLimits { get; set; }
    }
}
