//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Alert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public L_users()
        {
<<<<<<< HEAD
            this.Changed = new HashSet<h_alert>();
            this.Close = new HashSet<h_alert>();
            this.AcceptUser = new HashSet<h_alert>();
=======
            this.acceptUser = new HashSet<h_alert>();
            this.closeUser = new HashSet<h_alert>();
            this.lastChangeUser = new HashSet<h_alert>();
>>>>>>> 5db2146... start implementing new alert system (and sms controller)
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string LocationRoot { get; set; }
        public string AssetRoot { get; set; }
        public bool Locked { get; set; }
        public bool Blocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< HEAD
        public virtual ICollection<h_alert> Changed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_alert> Close { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_alert> AcceptUser { get; set; }
=======
        public virtual ICollection<h_alert> acceptUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_alert> closeUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_alert> lastChangeUser { get; set; }
>>>>>>> 5db2146... start implementing new alert system (and sms controller)
    }
}
