//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Alert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_variants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public l_variants()
        {
            this.l_controlLimits = new HashSet<l_controlLimits>();
        }
    
        public int id { get; set; }
        public string variantGroup { get; set; }
        public int c_trigger_id { get; set; }
        public string Comment { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual c_triggers c_triggers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<l_controlLimits> l_controlLimits { get; set; }
        public virtual L_users L_users { get; set; }
    }
}
