//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualSpatter_
    {
        public System.DateTime SpatterUpdateTime { get; set; }
        public Nullable<byte> Zone { get; set; }
        public Nullable<decimal> Spatters { get; set; }
        public Nullable<decimal> NbrWelds { get; set; }
        public Nullable<decimal> C_ZoneSpatters { get; set; }
        public Nullable<decimal> Last8HoursSpatterNbr { get; set; }
        public Nullable<decimal> Last8HoursNbrWelds { get; set; }
        public Nullable<decimal> Last8Hours_spatter { get; set; }
        public Nullable<long> id { get; set; }
    }
}
