//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertsAASPOT
    {
        public int id { get; set; }
        public System.DateTime C_timestamp { get; set; }
        public string location { get; set; }
        public string alarmobject { get; set; }
        public string info { get; set; }
        public int triggerCount { get; set; }
        public string state { get; set; }
        public string alertType { get; set; }
    }
}
