//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertsUsers
    {
        public System.DateTime C_timestamp { get; set; }
        public string location { get; set; }
        public string alarmobject { get; set; }
        public string locationTree { get; set; }
        public string info { get; set; }
        public string state { get; set; }
        public string Classification { get; set; }
        public string userAccept { get; set; }
        public Nullable<System.DateTime> AcceptTime { get; set; }
        public string userChanged { get; set; }
        public Nullable<System.DateTime> ChangedTime { get; set; }
        public string userClosed { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public string ResponsibleWeldMaster { get; set; }
        public int id { get; set; }
    }
}
