//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomaticWorkFlowULPlans
    {
        public Nullable<System.DateTime> LastInspectionTime { get; set; }
        public string UL_plan { get; set; }
        public int BuildBody_s { get; set; }
        public Nullable<System.TimeSpan> WorkTime { get; set; }
        public Nullable<int> WorkGroup { get; set; }
        public string WorkLocation { get; set; }
        public Nullable<int> Body_slast_30Min_start { get; set; }
        public Nullable<int> Body_slast_30Min_end { get; set; }
        public string Last30min_productionStatus { get; set; }
        public string onderhoudswerken { get; set; }
    }
}
