//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomaticPlanControleWeldBolt
    {
        public Nullable<System.DateTime> LastinspectionTime { get; set; }
        public string ULPlan { get; set; }
        public Nullable<int> WorkGroup { get; set; }
        public string WorkLocation { get; set; }
        public int ID { get; set; }
    }
}
