//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrownfieldLastMeasurement
    {
        public string Expr1 { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
        public byte Program { get; set; }
        public System.DateTime Date { get; set; }
        public string Shift { get; set; }
        public Nullable<short> NbrSplash { get; set; }
        public Nullable<short> NbrWeld { get; set; }
        public Nullable<short> NbrReweld { get; set; }
        public Nullable<float> AvgEnergy { get; set; }
        public Nullable<float> AvgPSF { get; set; }
        public Nullable<float> AvgOhm { get; set; }
        public Nullable<float> AvgUIP { get; set; }
        public Nullable<float> AvgWeldTIme { get; set; }
    }
}
