//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_NPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_NPT()
        {
            this.c_timer = new HashSet<c_timer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int OwnerId { get; set; }
        public string LoginPass { get; set; }
        public string LoginUser { get; set; }
        public string RemoreServer { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> enable_bit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_timer> c_timer { get; set; }
    }
}
