//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_Picture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_Picture()
        {
            this.c_Teardown = new HashSet<c_Teardown>();
        }
    
        public int id { get; set; }
        public int picturenbr { get; set; }
        public int picturename_id { get; set; }
        public bool idead { get; set; }
        public string Comment { get; set; }
        public string Description { get; set; }
        public System.DateTime timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_Teardown> c_Teardown { get; set; }
    }
}
