//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_Teardown
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_Teardown()
        {
            this.rt_Teardown = new HashSet<rt_Teardown>();
        }
    
        public string pjvspotid { get; set; }
        public string StartComment { get; set; }
        public int Plates { get; set; }
        public decimal Nomdiameter { get; set; }
        public int Id { get; set; }
        public int Type_ID { get; set; }
        public Nullable<int> c_job_id { get; set; }
        public int c_Picture_id { get; set; }
        public Nullable<int> ordinal { get; set; }
        public Nullable<bool> isdead { get; set; }
    
        public virtual c_Job c_Job { get; set; }
        public virtual c_Picture c_Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rt_Teardown> rt_Teardown { get; set; }
    }
}
