//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComparePitchV316
    {
        public string timerNumber { get; set; }
        public string lastWeldTime { get; set; }
        public string spotid { get; set; }
        public string Timer { get; set; }
        public string Variant { get; set; }
        public string AlternativeNumber { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> lastULControleTime { get; set; }
        public Nullable<double> TotalThickness { get; set; }
        public string SpotID { get; set; }
        public string Expr1 { get; set; }
    }
}
