//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionState
    {
        public string NoConnection { get; set; }
        public string TimerName { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<bool> onlineInBos6000 { get; set; }
    }
}
