//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoubleSpotCheck
    {
        public Nullable<int> SpotName { get; set; }
        public Nullable<int> WeldProgram { get; set; }
        public string TimerName { get; set; }
        public int ID { get; set; }
    }
}
