//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraControles
    {
        public string statusAdaptive { get; set; }
        public string Model { get; set; }
        public string Robot { get; set; }
        public int spot { get; set; }
        public string plan { get; set; }
        public Nullable<int> plannummer { get; set; }
        public string typecontrole { get; set; }
        public Nullable<System.DateTime> time_uit_adaptief { get; set; }
        public Nullable<System.TimeSpan> durationOFF { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> lastInspectiontime { get; set; }
    }
}
