//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraUltralogUitadaptief3
    {
        public string Timer { get; set; }
        public Nullable<int> spot { get; set; }
        public Nullable<bool> uitAdaptief { get; set; }
        public string NPT { get; set; }
        public string CDSID { get; set; }
        public Nullable<System.DateTime> Expr1 { get; set; }
    }
}
