//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_Midair
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public int SpotId { get; set; }
        public Nullable<short> ResisActual { get; set; }
        public Nullable<short> ResisRef { get; set; }
        public Nullable<byte> ElectrodeNo { get; set; }
        public Nullable<short> EnergyActual { get; set; }
        public Nullable<short> WeldTimeActual { get; set; }
        public Nullable<float> Iactual2 { get; set; }
    }
}
