//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_Nut_Bolt_Measure
    {
        public int ID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int SpotID { get; set; }
        public Nullable<int> wear { get; set; }
        public Nullable<double> I_demand { get; set; }
        public Nullable<double> I_Actual { get; set; }
        public string regulation { get; set; }
        public string BodyNr { get; set; }
        public Nullable<short> ElectrodeNr { get; set; }
        public Nullable<int> Weldtime { get; set; }
        public Nullable<int> EnergyActual { get; set; }
        public Nullable<int> EnergyRef { get; set; }
        public Nullable<int> ResistanceActual { get; set; }
        public Nullable<int> ResistanceRef { get; set; }
        public Nullable<int> ExpulsionTime { get; set; }
    }
}
