//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_weldmeasure
    {
        public int id { get; set; }
        public Nullable<System.DateTime> L_timeline_starttime { get; set; }
        public Nullable<System.DateTime> L_timeline_endtime { get; set; }
        public Nullable<int> L_timeline_id { get; set; }
        public Nullable<int> timerId { get; set; }
        public Nullable<short> progNo { get; set; }
        public Nullable<int> spotId { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> dt_FirstValue { get; set; }
        public Nullable<System.DateTime> dt_LastValue { get; set; }
        public Nullable<int> Expulsions { get; set; }
        public Nullable<int> Rewelds { get; set; }
        public Nullable<double> AVG_uirExpulsionTime { get; set; }
        public Nullable<double> AVG_voltage { get; set; }
        public Nullable<double> AVG_current { get; set; }
        public Nullable<double> AVG_weldtime { get; set; }
        public Nullable<double> AVG_enegery { get; set; }
        public Nullable<double> AVG_power { get; set; }
        public Nullable<double> AVG_resistance { get; set; }
        public Nullable<double> AVG_pulseWith { get; set; }
        public Nullable<double> AVG_uip { get; set; }
        public Nullable<double> AVG_stabilisationFactor { get; set; }
        public Nullable<int> MIN_uirExpulsionTime { get; set; }
        public Nullable<double> MIN_voltage { get; set; }
        public Nullable<double> MIN_current { get; set; }
        public Nullable<int> MIN_weldtime { get; set; }
        public Nullable<double> MIN_enegery { get; set; }
        public Nullable<double> MIN_power { get; set; }
        public Nullable<int> MIN_resistance { get; set; }
        public Nullable<double> MIN_pulseWith { get; set; }
        public Nullable<int> MIN_uip { get; set; }
        public Nullable<double> MIN_stabilisationFactor { get; set; }
        public Nullable<int> MAX_uirExpulsionTime { get; set; }
        public Nullable<double> MAX_voltage { get; set; }
        public Nullable<double> MAX_current { get; set; }
        public Nullable<int> MAX_weldtime { get; set; }
        public Nullable<double> MAX_enegery { get; set; }
        public Nullable<double> MAX_power { get; set; }
        public Nullable<int> MAX_resistance { get; set; }
        public Nullable<double> MAX_pulseWith { get; set; }
        public Nullable<int> MAX_uip { get; set; }
        public Nullable<double> MAX_stabilisationFactor { get; set; }
        public Nullable<double> STDEV_uirExpulsionTime { get; set; }
        public Nullable<double> STDEV_voltage { get; set; }
        public Nullable<double> STDEV_current { get; set; }
        public Nullable<double> STDEV_weldtime { get; set; }
        public Nullable<double> STDEV_enegery { get; set; }
        public Nullable<double> STDEV_power { get; set; }
        public Nullable<double> STDEV_resistance { get; set; }
        public Nullable<double> STDEV_pulseWith { get; set; }
        public Nullable<double> STDEV_uip { get; set; }
        public Nullable<double> STDEV_stabilisationFactor { get; set; }
    }
}
