//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterOptimalisation
    {
        public int id { get; set; }
        public int plateID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string NPT { get; set; }
        public string TimerName { get; set; }
        public Nullable<int> spotname { get; set; }
        public int Program { get; set; }
        public string pressure { get; set; }
        public string Squeeze { get; set; }
        public string KA1 { get; set; }
        public string Weld1 { get; set; }
        public string Cool_1 { get; set; }
        public string KA2 { get; set; }
        public string Weld2 { get; set; }
        public string Cool_2 { get; set; }
        public string KA3 { get; set; }
        public string Weld3 { get; set; }
        public string Hold { get; set; }
        public string pressureProfile_ { get; set; }
        public string Plateinfo { get; set; }
        public float thicknessplate1 { get; set; }
        public string Materialplate1 { get; set; }
        public string CoatingPlate1 { get; set; }
        public float thicknessplate2 { get; set; }
        public string Materialplate2 { get; set; }
        public string CoatingPlate2 { get; set; }
        public float thicknessplate3 { get; set; }
        public string Materialplate3 { get; set; }
        public string CoatingPlate3 { get; set; }
        public float thicknessplate4 { get; set; }
        public string Materialplate4 { get; set; }
        public string CoatingPlate4 { get; set; }
        public float totalThicknessDB { get; set; }
        public string ULinfo { get; set; }
        public string spot { get; set; }
        public Nullable<double> avgMeasuredThickness { get; set; }
        public Nullable<double> TotalThicknessUL { get; set; }
        public string WeldDatainfo { get; set; }
        public Nullable<System.DateTime> lastWeldShift { get; set; }
        public string number { get; set; }
        public Nullable<int> nbrWelds { get; set; }
        public Nullable<int> SpatterCount { get; set; }
        public Nullable<int> ReweldCount { get; set; }
        public Nullable<double> AVGpsf { get; set; }
        public Nullable<double> Avg_resistance { get; set; }
    }
}
