//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QISViewer
    {
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string TimerName { get; set; }
        public Nullable<int> program { get; set; }
        public string parameter { get; set; }
        public string bos6000Value { get; set; }
        public string RequiredValue { get; set; }
        public string remark { get; set; }
        public int id { get; set; }
    }
}
