//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_job11
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rt_job11()
        {
            this.rt_job_breakdown = new HashSet<rt_job_breakdown1>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<int> timerId { get; set; }
        public Nullable<int> ngac_rt_job_id { get; set; }
        public Nullable<System.DateTime> ts_Start { get; set; }
        public Nullable<System.DateTime> ts_End { get; set; }
        public Nullable<int> rt_weldmeasureprotddw_id_Start { get; set; }
        public Nullable<int> rt_weldmeasureprotddw_id_End { get; set; }
        public Nullable<int> rt_weldfaultprot_id_Start { get; set; }
        public Nullable<int> rt_weldfaultprot_id_End { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> rt_expulsion_count { get; set; }
        public Nullable<int> rt_weldmeasureprotddw_count { get; set; }
        public Nullable<int> rt_weldfaultprot_count { get; set; }
        public Nullable<int> rt_breakdown_count { get; set; }
        public Nullable<int> rt_weldmeasureprotddw_distinct { get; set; }
        public Nullable<int> rt_midair_count { get; set; }
    
        public virtual c_timer c_timer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rt_job_breakdown1> rt_job_breakdown { get; set; }
    }
}
