//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_job_breakdown
    {
        public int id { get; set; }
        public Nullable<int> rt_job_id { get; set; }
        public Nullable<int> rt_alarm_id { get; set; }
        public Nullable<System.DateTime> ts_breakdownStart { get; set; }
        public Nullable<System.DateTime> ts_breakdownEnd { get; set; }
        public Nullable<int> index { get; set; }
    
        public virtual rt_alarm rt_alarm { get; set; }
        public virtual rt_job rt_job { get; set; }
    }
}
