//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_job_expulsion
    {
        public int id { get; set; }
        public Nullable<int> rt_job_id { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<int> rt_weldmeasureprotddw_id { get; set; }
    }
}
