//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_user
    {
        public int id { get; set; }
        public Nullable<int> nptId { get; set; }
        public Nullable<int> c_UserId { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<decimal> protRecord_ID_login { get; set; }
        public Nullable<decimal> protRecord_ID_logout { get; set; }
        public Nullable<System.DateTime> dateTime_login { get; set; }
        public Nullable<System.DateTime> dateTime_logout { get; set; }
    
        public virtual c_NPT c_NPT { get; set; }
        public virtual c_user c_user { get; set; }
    }
}
