//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchplanNbr
    {
        public int id { get; set; }
        public System.DateTime InspectionTime { get; set; }
        public string timername { get; set; }
        public string spotname { get; set; }
        public string planName { get; set; }
        public int IndexOfTestSeq { get; set; }
        public Nullable<int> PlanLenght { get; set; }
        public Nullable<long> rowNbr { get; set; }
    }
}
