//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StabilityInDicationV316
    {
        public string NPT { get; set; }
        public string Timer { get; set; }
        public byte Program { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<short> nbrWelds { get; set; }
        public Nullable<float> StabiliteitsIni { get; set; }
    }
}
