//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartTeardown
    {
        public int id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> bodynbr { get; set; }
        public System.DateTime startTeardown1 { get; set; }
        public Nullable<System.DateTime> EndTeardown { get; set; }
    }
}
