//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoringsIngave_new
    {
        public int id { get; set; }
        public int userid { get; set; }
        public int Causeid { get; set; }
        public int Nameid { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<System.TimeSpan> starttime { get; set; }
        public Nullable<System.TimeSpan> Endtime { get; set; }
        public string worklocation { get; set; }
        public string userComment { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual StoringName StoringName { get; set; }
        public virtual StoringsCause StoringsCause { get; set; }
    }
}
