//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PicturePoints
    {
        public Nullable<int> PicturePointID { get; set; }
        public Nullable<int> PlanPointID { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<int> Xpos { get; set; }
        public Nullable<int> Ypos { get; set; }
        public bool Default { get; set; }
        public Nullable<int> Color { get; set; }
    }
}
