//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDTResults
    {
        public System.DateTime Date { get; set; }
        public Nullable<int> Number { get; set; }
        public string Model { get; set; }
        public Nullable<float> NuggetDemand { get; set; }
        public Nullable<float> TearDownNugget { get; set; }
        public Nullable<float> C1_3spot { get; set; }
        public string TDTResult { get; set; }
        public int ID { get; set; }
    }
}
