//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teardown
    {
        public int id { get; set; }
        public string spotid { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public Nullable<System.DateTime> measdate { get; set; }
        public Nullable<int> bodynbr { get; set; }
        public int comment_id { get; set; }
        public int result_id { get; set; }
        public int foutcode_id { get; set; }
        public int type_id { get; set; }
        public int picture_id { get; set; }
        public int plates { get; set; }
        public string startcomment { get; set; }
        public decimal nomdiameter { get; set; }
        public Nullable<decimal> measdiameter { get; set; }
    
        public virtual comment comment { get; set; }
        public virtual comment comment1 { get; set; }
        public virtual foutcode foutcode { get; set; }
        public virtual foutcode foutcode1 { get; set; }
        public virtual picture picture { get; set; }
        public virtual picture picture1 { get; set; }
        public virtual result result { get; set; }
        public virtual result result1 { get; set; }
        public virtual type type { get; set; }
        public virtual type type1 { get; set; }
    }
}
