//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeardownResults
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public int Spotid { get; set; }
        public Nullable<float> NuggetDemand { get; set; }
        public Nullable<float> TearDownNugget { get; set; }
        public string TeardownStatus { get; set; }
        public string TeardownEvalution { get; set; }
        public string TDTComment { get; set; }
    }
}
