//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerBreakdowns_WMActions
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string timerName { get; set; }
        public string fault { get; set; }
        public string timerfault { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public Nullable<int> downtime { get; set; }
        public Nullable<System.DateTime> interventionTime { get; set; }
        public string parameter { get; set; }
        public string oldValue { get; set; }
        public string newValue { get; set; }
        public string username { get; set; }
    }
}
