//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerBreakdownDatachange
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string location { get; set; }
        public string Expr1 { get; set; }
        public Nullable<System.DateTime> errorstarttime { get; set; }
        public Nullable<System.DateTime> errorEndTime { get; set; }
        public Nullable<System.TimeSpan> BreakdownTime { get; set; }
        public Nullable<int> Vyear { get; set; }
        public Nullable<int> Vweek { get; set; }
        public Nullable<int> Vday { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<System.DateTime> DataChangeTime { get; set; }
        public string Parameter { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string CDSID { get; set; }
        public string WMComment { get; set; }
        public string TimerFault { get; set; }
    }
}
