//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimerBreakdowns_busy
    {
        public string NPT { get; set; }
        public string TimerName { get; set; }
        public string Fault { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<int> BreakdownTime { get; set; }
        public int id { get; set; }
    }
}
