//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList_Remark
    {
        public int id { get; set; }
        public int TodoID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Remark { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ToDoList ToDoList { get; set; }
    }
}
