//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULplan_start
    {
        public int id { get; set; }
        public Nullable<int> planid { get; set; }
        public Nullable<int> lastplannumber { get; set; }
        public Nullable<System.DateTime> Startinspectiontime { get; set; }
        public Nullable<int> planlenght { get; set; }
        public Nullable<int> inspectorid { get; set; }
        public Nullable<int> StationId { get; set; }
        public Nullable<int> Worklocation { get; set; }
        public Nullable<int> bodynr { get; set; }
        public Nullable<int> plancounter { get; set; }
    }
}
