//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UltralogInspections
    {
        public int ID { get; set; }
        public int InspectionPlanID { get; set; }
        public int SpotID { get; set; }
        public string InspectorComment { get; set; }
        public int BodyNbr { get; set; }
        public int InspectorID { get; set; }
        public System.DateTime InspectionTime { get; set; }
        public int IndexOfTestSeq { get; set; }
        public bool Loose { get; set; }
        public bool OK { get; set; }
        public bool SmallNugget { get; set; }
        public bool StickWeld { get; set; }
        public bool BadTroughWeld { get; set; }
        public int StationID { get; set; }
        public Nullable<double> MeasuredThickness { get; set; }
        public Nullable<double> MinIdentation { get; set; }
        public Nullable<double> TotalThickness { get; set; }
        public Nullable<int> PlanLenght { get; set; }
    
        public virtual Inspectionplan Inspectionplan { get; set; }
        public virtual UltralogStations UltralogStations { get; set; }
        public virtual Users Users { get; set; }
    }
}
