//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingGunVariant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeldingGunVariant()
        {
            this.WeldingGun = new HashSet<WeldingGun>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<float> X { get; set; }
        public Nullable<float> Y { get; set; }
        public Nullable<float> Z { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingGun> WeldingGun { get; set; }
    }
}
