//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldfaultCount
    {
        public int id { get; set; }
        public string location { get; set; }
        public string NPT { get; set; }
        public string Timer { get; set; }
        public Nullable<long> countofTimerFaults { get; set; }
        public string WMComment { get; set; }
    }
}
