//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldFaultProtocol
    {
        public string NPT { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> FaultStart { get; set; }
        public Nullable<System.DateTime> FaultEnd { get; set; }
        public Nullable<int> breakdownTime { get; set; }
        public string errorCode1_txt { get; set; }
        public string errorCode2_txt { get; set; }
        public Nullable<int> CountFaultsInJob { get; set; }
        public Nullable<int> progNo { get; set; }
        public string CDSID { get; set; }
        public string WMComment { get; set; }
        public int id { get; set; }
    }
}
