//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingGun
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> ElectrodeNbr { get; set; }
        public Nullable<int> VariantID { get; set; }
        public Nullable<int> TimerID { get; set; }
        public string RobotType { get; set; }
    
        public virtual WeldingGunVariant WeldingGunVariant { get; set; }
    }
}
