//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Welding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xx_c_Spot
    {
        public int ID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<byte> Zone { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public int PlateCombinationtId { get; set; }
        public byte Program { get; set; }
        public int TimerID { get; set; }
        public byte ElectrodeDia { get; set; }
        public string AlternativeNumber { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public Nullable<int> JobCode { get; set; }
        public Nullable<float> NuggetDemand { get; set; }
        public Nullable<bool> HiddenSpot { get; set; }
        public Nullable<bool> GeoSpot { get; set; }
        public Nullable<int> SpotLeft { get; set; }
        public Nullable<int> SpotRight { get; set; }
    }
}
