//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.PJV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoiningPointData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JoiningPointData()
        {
            this.ProcessResult = new HashSet<ProcessResult>();
        }
    
        public int id { get; set; }
        public Nullable<int> joiningModelVariantDistinctId { get; set; }
        public Nullable<int> isDead { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<System.DateTime> C_lasttimestamp { get; set; }
        public string POINT_ID { get; set; }
        public string JOINT_PART_1 { get; set; }
        public string JOINT_PART_2 { get; set; }
        public string JOINT_PART_3 { get; set; }
        public string JOINT_PART_4 { get; set; }
        public Nullable<double> JM_X { get; set; }
        public Nullable<double> JM_Y { get; set; }
        public Nullable<double> JM_Z { get; set; }
        public Nullable<int> SPOT_PROCESS_NUMBER { get; set; }
        public string SPOT_GEOMETRY_TYPE { get; set; }
        public string PROCESS_LOCATION { get; set; }
        public string CAR_SIDE { get; set; }
        public string VARIANT { get; set; }
        public Nullable<double> SPOT_WELD_DIAMETER { get; set; }
        public string ELECTRODE_INTENDATION { get; set; }
        public string INSUFFICIENT_WELD_SPOT { get; set; }
        public Nullable<int> FUNCT_JOINT_No { get; set; }
        public string CONCEQUENCE_CLASS { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> Color_r { get; set; }
        public Nullable<int> Color_g { get; set; }
        public Nullable<int> Color_b { get; set; }
        public string LAYER_TYPE { get; set; }
        public Nullable<int> LAYER_NUMBER { get; set; }
        public Nullable<int> POINT_SYMBOL_NUMBER { get; set; }
        public string POSITION_TOLERANCE { get; set; }
        public string CO { get; set; }
        public string CO_INFO { get; set; }
        public string CO_ID { get; set; }
        public string CDSID_Last_Modified_By { get; set; }
        public string Joining_Model_Reference { get; set; }
        public string Local_ID { get; set; }
        public string USED_IN_VEHICLE { get; set; }
        public Nullable<int> WELD_CURVE_ID { get; set; }
        public Nullable<double> WELD_LENGTH_mm { get; set; }
        public string WELD_PROCESS_NUMBER { get; set; }
        public Nullable<double> WELD_SIZE_A { get; set; }
        public Nullable<double> WELD_SIZE_S { get; set; }
        public string WELD_CLASS { get; set; }
        public string ADDITIONAL_DEMANDS { get; set; }
        public Nullable<double> WELD_WIDTH { get; set; }
        public string GLUE_TRAP { get; set; }
        public string WELD_MATERIAL { get; set; }
        public string DEMANDS { get; set; }
        public Nullable<int> rev_created { get; set; }
        public Nullable<int> rev_modified { get; set; }
        public string PART_NAME { get; set; }
        public string FASTENER_ITEM { get; set; }
        public string FASTENER_TYPE { get; set; }
        public string AUX_DEMANDS { get; set; }
        public Nullable<double> VECTOR_VX_1 { get; set; }
        public Nullable<double> VECTOR_VX_2 { get; set; }
        public Nullable<double> VECTOR_VX_3 { get; set; }
        public Nullable<double> VECTOR_VY_1 { get; set; }
        public Nullable<double> VECTOR_VY_2 { get; set; }
        public Nullable<double> VECTOR_VY_3 { get; set; }
        public Nullable<double> VECTOR_VZ_1 { get; set; }
        public Nullable<double> VECTOR_VZ_2 { get; set; }
        public Nullable<double> VECTOR_VZ_3 { get; set; }
        public string jp_comment { get; set; }
    
        public virtual JoiningModelVariantDistinct JoiningModelVariantDistinct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessResult> ProcessResult { get; set; }
    }
}
