//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.PJV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoiningModelVariant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JoiningModelVariant()
        {
            this.JoiningModelVariantDistinct = new HashSet<JoiningModelVariantDistinct>();
        }
    
        public int id { get; set; }
        public Nullable<int> joiningFileId { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<System.DateTime> C_lasttimestamp { get; set; }
        public string name { get; set; }
        public string itemId { get; set; }
        public string specification { get; set; }
        public string spotWeldId { get; set; }
        public string process { get; set; }
        public Nullable<int> isDead { get; set; }
        public Nullable<int> rev_created { get; set; }
        public Nullable<int> rev_modified { get; set; }
    
        public virtual JoiningFile JoiningFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoiningModelVariantDistinct> JoiningModelVariantDistinct { get; set; }
    }
}
