//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.PJV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoiningFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JoiningFile()
        {
            this.JoiningModelVariant = new HashSet<JoiningModelVariant>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<System.DateTime> C_lasttimestamp { get; set; }
        public string fullFileName { get; set; }
        public string filename { get; set; }
        public Nullable<System.DateTime> fileDateTime { get; set; }
        public Nullable<System.DateTime> createDateTime { get; set; }
        public Nullable<System.DateTime> modifiedDateTime { get; set; }
        public string propertyInfo { get; set; }
        public Nullable<int> isDead { get; set; }
        public Nullable<int> rev_created { get; set; }
        public Nullable<int> rev_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoiningModelVariant> JoiningModelVariant { get; set; }
    }
}
