//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.PJV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GADATAEntitiesPJV : DbContext
    {
        public GADATAEntitiesPJV()
            : base("name=GADATAEntitiesPJV")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JoiningFile> JoiningFile { get; set; }
        public virtual DbSet<JoiningModelVariant> JoiningModelVariant { get; set; }
        public virtual DbSet<JoiningModelVariantDistinct> JoiningModelVariantDistinct { get; set; }
        public virtual DbSet<JoiningPointData> JoiningPointData { get; set; }
        public virtual DbSet<L_operation> L_operation { get; set; }
        public virtual DbSet<ProcessResult> ProcessResult { get; set; }
        public virtual DbSet<RobotDetail> RobotDetail { get; set; }
        public virtual DbSet<RobotPoint> RobotPoint { get; set; }
        public virtual DbSet<RobotProgram> RobotProgram { get; set; }
        public virtual DbSet<RobotRoutine> RobotRoutine { get; set; }
        public virtual DbSet<SummaryResult> SummaryResult { get; set; }
        public virtual DbSet<ProcessPoints> ProcessPoints { get; set; }
    }
}
