//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.PJV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RobotPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RobotPoint()
        {
            this.ProcessResult = new HashSet<ProcessResult>();
        }
    
        public int id { get; set; }
        public Nullable<int> isDead { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<System.DateTime> C_lasttimestamp { get; set; }
        public string v_name { get; set; }
        public Nullable<int> robotRoutineId { get; set; }
        public Nullable<int> datatype { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> Z { get; set; }
        public Nullable<int> switchon { get; set; }
        public string processValue1 { get; set; }
        public string processValue2 { get; set; }
        public string frame { get; set; }
        public string tool { get; set; }
        public string vel { get; set; }
        public Nullable<int> remote_tool { get; set; }
        public string spd { get; set; }
        public string traj { get; set; }
        public string zone { get; set; }
        public Nullable<int> programLine { get; set; }
        public string process_s { get; set; }
        public Nullable<int> rev_created { get; set; }
        public Nullable<int> rev_modified { get; set; }
        public string pp_comment { get; set; }
        public Nullable<double> R_VX_1 { get; set; }
        public Nullable<double> R_VX_2 { get; set; }
        public Nullable<double> R_VX_3 { get; set; }
        public Nullable<double> R_VY_1 { get; set; }
        public Nullable<double> R_VY_2 { get; set; }
        public Nullable<double> R_VY_3 { get; set; }
        public Nullable<double> R_VZ_1 { get; set; }
        public Nullable<double> R_VZ_2 { get; set; }
        public Nullable<double> R_VZ_3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessResult> ProcessResult { get; set; }
        public virtual RobotRoutine RobotRoutine { get; set; }
    }
}
