//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAddInEquipmentDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_datasource
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string ConnectionString { get; set; }
        public bool isAlertSource { get; set; }
        public string PwList { get; set; }
    }
}
