#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAddInEquipmentDatabase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GADATA")]
	public partial class DataClassesGADATADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesGADATADataContext() : 
				base(global::ExcelAddInEquipmentDatabase.Properties.Settings.Default.GADATAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGADATADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGADATADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGADATADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGADATADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Robot> Robots
		{
			get
			{
				return this.GetTable<Robot>();
			}
		}
		
		public System.Data.Linq.Table<ASSETS_fromMX7> ASSETS_fromMX7s
		{
			get
			{
				return this.GetTable<ASSETS_fromMX7>();
			}
		}
		
		public System.Data.Linq.Table<ASSET> ASSETs
		{
			get
			{
				return this.GetTable<ASSET>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Volvo.Robots")]
	public partial class Robot
	{
		
		private string _controller_type;
		
		private string _table;
		
		private int _id;
		
		private string _controller_name;
		
		private string _location;
		
		private string _ownership;
		
		private string _Plant;
		
		private string _Area;
		
		private string _SubArea;
		
		private string _server;
		
		public Robot()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controller_type", DbType="VarChar(32)")]
		public string controller_type
		{
			get
			{
				return this._controller_type;
			}
			set
			{
				if ((this._controller_type != value))
				{
					this._controller_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[table]", Storage="_table", DbType="VarChar(23) NOT NULL", CanBeNull=false)]
		public string table
		{
			get
			{
				return this._table;
			}
			set
			{
				if ((this._table != value))
				{
					this._table = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controller_name", DbType="VarChar(50)")]
		public string controller_name
		{
			get
			{
				return this._controller_name;
			}
			set
			{
				if ((this._controller_name != value))
				{
					this._controller_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(256)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ownership", DbType="VarChar(256)")]
		public string ownership
		{
			get
			{
				return this._ownership;
			}
			set
			{
				if ((this._ownership != value))
				{
					this._ownership = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plant", DbType="VarChar(3)")]
		public string Plant
		{
			get
			{
				return this._Plant;
			}
			set
			{
				if ((this._Plant != value))
				{
					this._Plant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(25)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubArea", DbType="VarChar(25)")]
		public string SubArea
		{
			get
			{
				return this._SubArea;
			}
			set
			{
				if ((this._SubArea != value))
				{
					this._SubArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_server", DbType="VarChar(50)")]
		public string server
		{
			get
			{
				return this._server;
			}
			set
			{
				if ((this._server != value))
				{
					this._server = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Volvo.ASSETS_fromMX7")]
	public partial class ASSETS_fromMX7
	{
		
		private string _SYSTEMID;
		
		private string _LOCATION;
		
		private string _LocationDescription;
		
		private string _ASSETNUM;
		
		private string _AssetDescription;
		
		private string _LocationTree;
		
		public ASSETS_fromMX7()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMID", DbType="VarChar(255)")]
		public string SYSTEMID
		{
			get
			{
				return this._SYSTEMID;
			}
			set
			{
				if ((this._SYSTEMID != value))
				{
					this._SYSTEMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(255)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this._LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationDescription", DbType="VarChar(255)")]
		public string LocationDescription
		{
			get
			{
				return this._LocationDescription;
			}
			set
			{
				if ((this._LocationDescription != value))
				{
					this._LocationDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSETNUM", DbType="VarChar(255)")]
		public string ASSETNUM
		{
			get
			{
				return this._ASSETNUM;
			}
			set
			{
				if ((this._ASSETNUM != value))
				{
					this._ASSETNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetDescription", DbType="VarChar(255)")]
		public string AssetDescription
		{
			get
			{
				return this._AssetDescription;
			}
			set
			{
				if ((this._AssetDescription != value))
				{
					this._AssetDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationTree", DbType="VarChar(MAX)")]
		public string LocationTree
		{
			get
			{
				return this._LocationTree;
			}
			set
			{
				if ((this._LocationTree != value))
				{
					this._LocationTree = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Volvo.ASSETS")]
	public partial class ASSET
	{
		
		private string _SYSTEMID;
		
		private string _LOCATION;
		
		private string _ASSETNUM;
		
		private string _AssetDescription;
		
		private string _LocationTree;
		
		private string _controller_name;
		
		private string _controller_type;
		
		private System.Nullable<int> _controller_id;
		
		public ASSET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMID", DbType="VarChar(255)")]
		public string SYSTEMID
		{
			get
			{
				return this._SYSTEMID;
			}
			set
			{
				if ((this._SYSTEMID != value))
				{
					this._SYSTEMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(255)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this._LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSETNUM", DbType="VarChar(255)")]
		public string ASSETNUM
		{
			get
			{
				return this._ASSETNUM;
			}
			set
			{
				if ((this._ASSETNUM != value))
				{
					this._ASSETNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetDescription", DbType="VarChar(255)")]
		public string AssetDescription
		{
			get
			{
				return this._AssetDescription;
			}
			set
			{
				if ((this._AssetDescription != value))
				{
					this._AssetDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationTree", DbType="VarChar(MAX)")]
		public string LocationTree
		{
			get
			{
				return this._LocationTree;
			}
			set
			{
				if ((this._LocationTree != value))
				{
					this._LocationTree = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controller_name", DbType="VarChar(50)")]
		public string controller_name
		{
			get
			{
				return this._controller_name;
			}
			set
			{
				if ((this._controller_name != value))
				{
					this._controller_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controller_type", DbType="VarChar(32)")]
		public string controller_type
		{
			get
			{
				return this._controller_type;
			}
			set
			{
				if ((this._controller_type != value))
				{
					this._controller_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controller_id", DbType="Int")]
		public System.Nullable<int> controller_id
		{
			get
			{
				return this._controller_id;
			}
			set
			{
				if ((this._controller_id != value))
				{
					this._controller_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
