//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAddInEquipmentDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquiEntities : DbContext
    {
        public EquiEntities()
            : base("name=EquiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<c_datasource> c_datasource { get; set; }
        public virtual DbSet<c_userRoles> c_userRoles { get; set; }
        public virtual DbSet<h_usersPermisions> h_usersPermisions { get; set; }
        public virtual DbSet<L_users> L_users { get; set; }
        public virtual DbSet<QUERYParameters> QUERYParameters { get; set; }
        public virtual DbSet<QUERYS> QUERYS { get; set; }
    }
}
