//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAddInEquipmentDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERYParameters
    {
        public string SYSTEM { get; set; }
        public string NAME { get; set; }
        public string SETNAME { get; set; }
        public string DISCRIPTION { get; set; }
        public string Parameter { get; set; }
        public string Value { get; set; }
    }
}
