CREATE TABLE [NGAC].[rt_TipDressLogFile] (
    [id]                       INT           IDENTITY (1, 1) NOT NULL,
    [_timestamp]               DATETIME      NULL,
    [rt_csv_file_id]           INT           NULL,
    [Date Time]                VARCHAR (MAX) NULL,
    [Tool_Nr]                  VARCHAR (MAX) NULL,
    [Dress_Num]                VARCHAR (MAX) NULL,
    [Weld_Counter]             VARCHAR (MAX) NULL,
    [Dress_Reason]             VARCHAR (MAX) NULL,
    [Weld_Result]              VARCHAR (MAX) NULL,
    [Length_Fixed_Result]      VARCHAR (MAX) NULL,
    [Length_Move_Result]       VARCHAR (MAX) NULL,
    [Max_Wear_Fixed]           VARCHAR (MAX) NULL,
    [Wear_Fixed]               VARCHAR (MAX) NULL,
    [DiffFrLastWear_Fixed]     VARCHAR (MAX) NULL,
    [Max_Wear_Move]            VARCHAR (MAX) NULL,
    [Wear_Move]                VARCHAR (MAX) NULL,
    [DiffFrLastWear_Move]      VARCHAR (MAX) NULL,
    [MaxDiffFrLastMeas]        VARCHAR (MAX) NULL,
    [Current_TipWear]          VARCHAR (MAX) NULL,
    [TipWearRatio]             VARCHAR (MAX) NULL,
    [Dress_Time1]              VARCHAR (MAX) NULL,
    [Dress_Pressure1]          VARCHAR (MAX) NULL,
    [Dress_Time2]              VARCHAR (MAX) NULL,
    [Dress_Pressure2]          VARCHAR (MAX) NULL,
    [CleanDress_Time]          VARCHAR (MAX) NULL,
    [CleanDress_Pressure]      VARCHAR (MAX) NULL,
    [Time_DressCycleTime]      VARCHAR (MAX) NULL,
    [ErrorType]                VARCHAR (MAX) NULL,
    [ExtraInfo]                VARCHAR (MAX) NULL,
    [GunTCP_X]                 VARCHAR (MAX) NULL,
    [GunTCP_Y]                 VARCHAR (MAX) NULL,
    [GunTCP_Z]                 VARCHAR (MAX) NULL,
    [GunRefTCP_X]              VARCHAR (MAX) NULL,
    [GunRefTCP_Y]              VARCHAR (MAX) NULL,
    [GunRefTCP_Z]              VARCHAR (MAX) NULL,
    [NomTCP_X]                 VARCHAR (MAX) NULL,
    [NomTCP_Y]                 VARCHAR (MAX) NULL,
    [NomTCP_Z]                 VARCHAR (MAX) NULL,
    [Tool_NrHs]                VARCHAR (MAX) NULL,
    [ChkDrWear_Fixed_Result]   VARCHAR (MAX) NULL,
    [ChkDrWear_Move_Result]    VARCHAR (MAX) NULL,
    [FxSens_SetupVal]          VARCHAR (MAX) NULL,
    [FxSens_StartVal]          VARCHAR (MAX) NULL,
    [FxSens_PrevVal]           VARCHAR (MAX) NULL,
    [FxSens_PrevWare]          VARCHAR (MAX) NULL,
    [FxSens_DiffValue]         VARCHAR (MAX) NULL,
    [FxSens_MaxSensZComp]      VARCHAR (MAX) NULL,
    [FxSens_WarmSensZComp]     VARCHAR (MAX) NULL,
    [FxSens_FlPinPrevVal]      VARCHAR (MAX) NULL,
    [FxSens_FlPinSetupVal]     VARCHAR (MAX) NULL,
    [FxSens_FlPinPhysActVal]   VARCHAR (MAX) NULL,
    [FxSens_FlPinPhysSetupVal] VARCHAR (MAX) NULL,
    [Internal_Arg]             VARCHAR (MAX) NULL
);

