//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Supervision.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GADATAEntities2 : DbContext
    {
        public GADATAEntities2()
            : base("name=GADATAEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C3G_Supervisie> C3G_Supervisie { get; set; }
        public virtual DbSet<C4G_Supervisie> C4G_Supervisie { get; set; }
        public virtual DbSet<S4C_Supervisie> S4C_Supervisie { get; set; }
        public virtual DbSet<STO_Supervisie> STO_Supervisie { get; set; }
        public virtual DbSet<Timeline> Timeline { get; set; }
        public virtual DbSet<Alerts_Supervisie> Alerts_Supervisie { get; set; }
    }
}
