
--uitgeschreven stukken join WO NuM 
select 
 WORKORDER.WONUM
,WORKORDER.DESCRIPTION
,WORKORDER.ASSETNUM
,WORKORDER.LOCATION
,WPITEM.ITEMNUM
,WPITEM.DESCRIPTION
,WPITEM.ITEMQTY
,WPITEM.LOCATION MagLocation
,WPITEM.LINECOST
,WPITEM.REQUESTBY
from MAXIMO.WORKORDER WORKORDER  
LEFT JOIN MAXIMO.WPITEM WPITEM on WPITEM.WONUM = WORKORDER.WONUM
where WORKORDER.WONUM = '8085851';


--uigeschreven stukken 
select 
 WPITEM.ITEMNUM
,WPITEM.DESCRIPTION
,WPITEM.ITEMQTY
,WPITEM.LOCATION
,WPITEM.LINECOST
,WPITEM.REQUESTBY
,WPITEM.WONUM
from MAXIMO.WPITEM WPITEM
--where WPITEM.ITEMNUM LIKE '%6062870020%';
where WPITEM.WONUM = '8085851';

--workorder change history
select 
 WOSTATUS.WONUM
,WOSTATUS.STATUS
,WOSTATUS.CHANGEDATE
,WOSTATUS.MEMO
,WOSTATUS.SITEID
from MAXIMO.WOSTATUS WOSTATUS
where WOSTATUS.WONUM = '8085851';