define _assets = 'UR%';
define _locations ='%';
define _StartDate = '2017-01-01 00:00:00';
define _EndDate = '2018-01-01 00:00:00';
define _ChangedAfter = '1900-01-01 00:00:00';
define _Owngergroup = '%';
define _Reportedby = '%';
define _Wonum = '8563831';

--WO DETAILS
select 
 to_number(WORKORDER.WONUM) WONUM
,WORKORDER.LOCATION
,WORKORDER.STATUS ActStatus
,WORKORDER.DESCRIPTION
,WORKORDER.SCHEDSTART
,WORKORDER.ESTDUR 
,(WOSTATUSwappr.CHANGEDATE || ' U:' || WOSTATUSwappr.CHANGEBY) Swppr
,(WOSTATUSinprg.CHANGEDATE || ' U:' || WOSTATUSinprg.CHANGEBY) Sinprg
,(WOSTATUScomp.CHANGEDATE || ' U:' || WOSTATUScomp.CHANGEBY) Scomp

,(WPLABOR.LABORCODE || ' h:' ||WPLABOR.LABORHRS) Planned
,(LABTRANS.LABORCODE || 'h:' || LABTRANS.REGULARHRS) Actual

,WORKORDER.STATUSDATE lastChanged
,WORKORDER.OWNERGROUP
,WORKORDER.ASSETNUM
,WORKORDER.ASSIGNEDOWNERGROUP
,WORKORDER.CXMATERIALBOXID

from MAXIMO.WORKORDER WORKORDER 
left join MAXIMO.WPLABOR WPLABOR on WPLABOR.WONUM = WORKORDER.WONUM
left join MAXIMO.LABTRANS  LABTRANS on LABTRANS.REFWO = WORKORDER.WONUM
left join MAXIMO.WOSTATUS WOSTATUSwappr on (WOSTATUSwappr.WONUM = WORKORDER.WONUM) AND (WOSTATUSwappr.STATUS = 'WAPPR')
left join MAXIMO.WOSTATUS WOSTATUSinprg on (WOSTATUSinprg.WONUM = WORKORDER.WONUM) AND (WOSTATUSinprg.STATUS = 'INPRG')
left join MAXIMO.WOSTATUS WOSTATUScomp on (WOSTATUScomp.WONUM = WORKORDER.WONUM) AND (WOSTATUScomp.STATUS = 'COMP')
where 
 WORKORDER.ASSETNUM LIKE '&_assets'
 AND
 WORKORDER.LOCATION LIKE '&_locations'
 AND
 WORKORDER.REPORTDATE > TO_TIMESTAMP('&_StartDate', 'yyyy/mm/dd hh24:mi:ss')
 AND
 WORKORDER.STATUSDATE < TO_TIMESTAMP('&_EndDate', 'yyyy/mm/dd hh24:mi:ss')
 AND
 WORKORDER.CHANGEDATE > TO_TIMESTAMP('&_ChangedAfter', 'yyyy/mm/dd hh24:mi:ss')
 AND
 WORKORDER.OWNERGROUP LIKE '&_Owngergroup'
 AND
 WORKORDER.REPORTEDBY LIKE '&_Reportedby'
 AND
 WORKORDER.WONUM LIKE  '&_Wonum' 
 ORDER BY WORKORDER.STATUSDATE;