//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Tiplife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C3G_SBCUData
    {
        public Nullable<System.DateTime> tool_timestamp { get; set; }
        public string RobotName { get; set; }
        public string tool_id { get; set; }
        public Nullable<double> Dmeas { get; set; }
        public Nullable<double> Dsetup { get; set; }
        public Nullable<double> ToolX { get; set; }
        public Nullable<double> ToolY { get; set; }
        public Nullable<double> ToolZ { get; set; }
        public Nullable<double> Toola { get; set; }
        public Nullable<double> Toole { get; set; }
        public Nullable<double> Toolr { get; set; }
        public Nullable<bool> Longcheck { get; set; }
        public Nullable<bool> TcpUpdate { get; set; }
        public Nullable<int> Vyear { get; set; }
        public Nullable<int> Vweek { get; set; }
        public Nullable<int> Vday { get; set; }
        public Nullable<int> RefAVG { get; set; }
        public Nullable<int> RefSTDEC { get; set; }
        public Nullable<double> LCL { get; set; }
        public Nullable<double> UCL { get; set; }
        public Nullable<int> RefDp { get; set; }
        public Nullable<int> RefSS { get; set; }
        public int ID { get; set; }
        public Nullable<byte> gunnum { get; set; }
        public string LocationTree { get; set; }
    }
}
