//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Tiplife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCP_LOG
    {
        public string controller_name { get; set; }
        public string LocationTree { get; set; }
        public string ClassificationTree { get; set; }
        public string Toolname { get; set; }
        public string alarmobject { get; set; }
        public int id { get; set; }
        public Nullable<int> rt_csv_file_id { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string Tool_Name { get; set; }
        public Nullable<int> SetUp_No { get; set; }
        public Nullable<double> Tool_Diff_X { get; set; }
        public Nullable<double> Tool_Diff_Y { get; set; }
        public Nullable<double> Tool_Diff_Z { get; set; }
        public Nullable<double> Tool_Tol_X { get; set; }
        public Nullable<double> Tool_Tol_Y { get; set; }
        public Nullable<double> Tool_Tol_Z { get; set; }
        public Nullable<double> Old_TCP_X { get; set; }
        public Nullable<double> Old_TCP_Y { get; set; }
        public Nullable<double> Old_TCP_Z { get; set; }
        public Nullable<double> New_TCP_X { get; set; }
        public Nullable<double> New_TCP_Y { get; set; }
        public Nullable<double> New_TCP_Z { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<double> SetupTCP_X { get; set; }
        public Nullable<double> SetupTCP_Y { get; set; }
        public Nullable<double> SetupTCP_Z { get; set; }
        public Nullable<double> DeltaRef { get; set; }
    }
}
