//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Tiplife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipDressCycleTimeREMO
    {
        public int id { get; set; }
        public string controller_name { get; set; }
        public string LocationTree { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<double> CT { get; set; }
    }
}
