//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Tiplife.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipMonitor
    {
        public string Robot { get; set; }
        public Nullable<short> Tool_Nr { get; set; }
        public System.DateTime Date_time { get; set; }
        public Nullable<short> nDress { get; set; }
        public Nullable<short> nWelds { get; set; }
        public Nullable<double> WearRatio { get; set; }
        public Nullable<double> pWear { get; set; }
        public Nullable<double> nRspots { get; set; }
        public Nullable<double> nRcars { get; set; }
        public Nullable<int> TipAge_h_ { get; set; }
        public Nullable<System.DateTime> LastTipchange { get; set; }
        public Nullable<double> Time_DressCycleTime { get; set; }
        public int id { get; set; }
        public string LocationTree { get; set; }
        public Nullable<double> MagicFiXedWear { get; set; }
        public string Status { get; set; }
        public Nullable<double> RobotWear { get; set; }
    }
}
