//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.Gadata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeline
    {
        public string Location { get; set; }
        public string Robotname { get; set; }
        public string Type { get; set; }
        public string Errortype { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> Logcode { get; set; }
        public Nullable<int> Severity { get; set; }
        public string Logtekst { get; set; }
        public Nullable<int> DOWNTIME { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> day { get; set; }
        public string Shift { get; set; }
        public string Ploeg { get; set; }
        public string Object { get; set; }
        public string Subgroup { get; set; }
        public int id { get; set; }
    }
}
