//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_timer_class
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> cBoschViewMask { get; set; }
        public Nullable<int> cErrorMask { get; set; }
        public Nullable<int> cSeverityMask { get; set; }
    }
}
