//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NPT()
        {
            this.Timer = new HashSet<Timer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int OwnerId { get; set; }
        public string LoginPass { get; set; }
        public string LoginUser { get; set; }
        public string RemoreServer { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> enable_bit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timer> Timer { get; set; }
    }
}
