//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSC_rt_job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VWSC_rt_job()
        {
            this.rt_job_breakdown = new HashSet<VWSC_rt_job_breakdown>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<int> timerId { get; set; }
        public Nullable<int> ngac_rt_job_id { get; set; }
        public Nullable<System.DateTime> ts_Start { get; set; }
        public Nullable<System.DateTime> ts_End { get; set; }
        public Nullable<int> rt_weldmeasureprotddw_id_Start { get; set; }
        public Nullable<int> rt_weldmeasureprotddw_id_End { get; set; }
        public Nullable<int> rt_weldfaultprot_id_Start { get; set; }
        public Nullable<int> rt_weldfaultprot_id_End { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> rt_expulsion_count { get; set; }
        public Nullable<int> rt_weldmeasureprotddw_count { get; set; }
        public Nullable<int> rt_weldfaultprot_count { get; set; }
        public Nullable<int> rt_breakdown_count { get; set; }
    
        public virtual VWSC_c_Timer Timer { get; set; }
        public virtual VWSC_c_Timer Timer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_job_breakdown> rt_job_breakdown { get; set; }
    }
}
