//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSC_c_bosch_view
    {
        public int id { get; set; }
        public string view { get; set; }
        public Nullable<int> enable_bit { get; set; }
        public Nullable<int> poll_rate { get; set; }
        public Nullable<int> flag { get; set; }
        public string rt_table { get; set; }
        public Nullable<int> day_limit { get; set; }
    }
}
