//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GADATAEntitiesVwsc : DbContext
    {
        public GADATAEntitiesVwsc()
            : base("name=GADATAEntitiesVwsc")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<c_error> c_error { get; set; }
        public virtual DbSet<c_service_setup> c_service_setup { get; set; }
        public virtual DbSet<c_severity> c_severity { get; set; }
        public virtual DbSet<c_timer_class> c_timer_class { get; set; }
        public virtual DbSet<L_operation> L_operation { get; set; }
        public virtual DbSet<rt_active_info> rt_active_info { get; set; }
        public virtual DbSet<c_bosch_view> c_bosch_view { get; set; }
        public virtual DbSet<rt_communication_state> rt_communication_state { get; set; }
        public virtual DbSet<NPT> NPT { get; set; }
        public virtual DbSet<Timer> Timer { get; set; }
    }
}
