//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSC_c_timer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VWSC_c_timer()
        {
            this.rt_active_info = new HashSet<VWSC_rt_active_info>();
            this.rt_alarm = new HashSet<VWSC_rt_alarm>();
            this.rt_communication_state = new HashSet<VWSC_rt_communication_state>();
            this.rt_job = new HashSet<VWSC_rt_job>();
            this.rt_weldfault = new HashSet<VWSC_rt_weldfault>();
            this.rt_weldmeasureprotddw = new HashSet<VWSC_rt_weldmeasureprotddw>();
            this.L_operation = new HashSet<VWSC_L_operation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NptId { get; set; }
        public string Robot { get; set; }
        public string location { get; set; }
        public Nullable<int> c_timer_class_id { get; set; }
        public Nullable<int> enable_bit { get; set; }
        public string LocationTree { get; set; }
        public string Assetnum { get; set; }
        public string ResponsibleWeldMaster { get; set; }
        public string Station { get; set; }
        public string Line { get; set; }
    
        public virtual VWSC_c_NPT c_NPT { get; set; }
        public virtual VWSC_c_timer_class c_timer_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_active_info> rt_active_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_alarm> rt_alarm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_communication_state> rt_communication_state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_job> rt_job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_weldfault> rt_weldfault { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_weldmeasureprotddw> rt_weldmeasureprotddw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_L_operation> L_operation { get; set; }
    }
}
