//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSC_c_severity
    {
        public int id { get; set; }
        public Nullable<int> enable_bit { get; set; }
        public string isError_txt { get; set; }
        public Nullable<int> value { get; set; }
    }
}
