//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSC_rt_spot
    {
        public int id { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<int> timerId { get; set; }
        public Nullable<int> spotId { get; set; }
        public string spotname { get; set; }
        public Nullable<int> pjv_joiningpointdata_id { get; set; }
        public string vwscComment { get; set; }
        public Nullable<int> Comment1 { get; set; }
        public Nullable<int> Comment2 { get; set; }
        public Nullable<int> Comment3 { get; set; }
        public Nullable<int> weldProgramNo { get; set; }
        public Nullable<int> isDead { get; set; }
    }
}
