//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSC_c_timer_class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VWSC_c_timer_class()
        {
            this.Timer = new HashSet<VWSC_c_Timer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> cBoschViewMask { get; set; }
        public Nullable<int> cErrorMask { get; set; }
        public Nullable<int> cSeverityMask { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_c_Timer> Timer { get; set; }
    }
}
