//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSC_rt_alarm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VWSC_rt_alarm()
        {
            this.rt_job_breakdown = new HashSet<VWSC_rt_job_breakdown>();
        }
    
        public int id { get; set; }
        public Nullable<int> timerId { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<int> protRecord_ID { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<int> errorCode1 { get; set; }
        public string errorCode1_txt { get; set; }
        public Nullable<int> errorCode2 { get; set; }
        public string errorCode2_txt { get; set; }
        public Nullable<bool> isError { get; set; }
        public string isError_txt { get; set; }
    
        public virtual VWSC_c_Timer Timer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_job_breakdown> rt_job_breakdown { get; set; }
    }
}
