//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VWSC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWSC_c_Timer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VWSC_c_Timer()
        {
            this.rt_active_info = new HashSet<VWSC_rt_active_info>();
            this.L_operation = new HashSet<VWSC_L_operation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> NptId { get; set; }
        public string Robot { get; set; }
        public string location { get; set; }
        public Nullable<int> c_timer_class_id { get; set; }
        public Nullable<int> enable_bit { get; set; }
    
        public virtual VWSC_c_NPT NPT { get; set; }
        public virtual VWSC_c_timer_class c_timer_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_rt_active_info> rt_active_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VWSC_L_operation> L_operation { get; set; }
    }
}
