//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveState
    {
        public string controller_name { get; set; }
        public System.DateTime C_timestamp { get; set; }
        public int program_number { get; set; }
        public int application_error { get; set; }
        public int operating_mode { get; set; }
        public int at_home { get; set; }
        public string FullLogtext { get; set; }
    }
}
