//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSETS
    {
        public int id { get; set; }
        public string SYSTEMID { get; set; }
        public string LOCATION { get; set; }
        public string ASSETNUM { get; set; }
        public string AssetDescription { get; set; }
        public string LocationTree { get; set; }
        public string ClassDescription { get; set; }
        public string ClassStructureId { get; set; }
        public string CLassificationId { get; set; }
        public string ClassificationTree { get; set; }
        public string Station { get; set; }
        public string Area { get; set; }
        public string Team { get; set; }
        public string controller_name { get; set; }
        public string controller_type { get; set; }
        public Nullable<int> controller_id { get; set; }
        public Nullable<long> controller_ToolID { get; set; }
        public string ResponsibleTechnicianTeam { get; set; }
        public string ResponsibleProductionTeam { get; set; }
    }
}
