//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breakdown
    {
        public string location { get; set; }
        public string AssetID { get; set; }
        public string Logtype { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string Logcode { get; set; }
        public string Severity { get; set; }
        public string logtext { get; set; }
        public string Fulllogtext { get; set; }
        public Nullable<int> Response { get; set; }
        public Nullable<int> Downtime { get; set; }
        public string Classification { get; set; }
        public string Subgroup { get; set; }
        public Nullable<int> Category { get; set; }
        public double refId { get; set; }
        public string LocationTree { get; set; }
        public string ClassTree { get; set; }
        public string controller_name { get; set; }
        public string controller_type { get; set; }
    }
}
