//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_datasource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_datasource()
        {
            this.c_LogClassRules = new HashSet<c_LogClassRules>();
        }
    
        public int @int { get; set; }
        public string DataSourceName { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string ConnectionString { get; set; }
        public bool isAlertSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_LogClassRules> c_LogClassRules { get; set; }
    }
}
