//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_job
    {
        public int id { get; set; }
        public bool enabled { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int c_schedule_id { get; set; }
        public int c_datasource_id { get; set; }
        public string sqlCommand { get; set; }
        public int ordinal { get; set; }
        public int interval { get; set; }
        public int intervalCounter { get; set; }
        public bool continueOnJobFailure { get; set; }
        public Nullable<int> maxRuntime { get; set; }
        public Nullable<int> warnRuntime { get; set; }
    
        public virtual c_datasource c_datasource { get; set; }
        public virtual c_schedule c_schedule { get; set; }
    }
}
