//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_LogClassRules
    {
        public int id { get; set; }
        public int c_logClassSystem_id { get; set; }
        public Nullable<int> coderangeStart { get; set; }
        public Nullable<int> coderangeEnd { get; set; }
        public string textSearch { get; set; }
        public string I_comment { get; set; }
        public int c_ClassificationId { get; set; }
        public int c_SubgroupId { get; set; }
    
        public virtual c_Classification c_Classification { get; set; }
        public virtual c_logClassSystem c_logClassSystem { get; set; }
        public virtual c_Subgroup c_Subgroup { get; set; }
    }
}
