//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_LogClassRules
    {
        public int id { get; set; }
        public Nullable<int> Err_start { get; set; }
        public Nullable<int> Err_end { get; set; }
        public string Err_text { get; set; }
        public string I_comment { get; set; }
        public Nullable<int> c_ClassificationId { get; set; }
        public Nullable<int> c_SubgroupId { get; set; }
        public int c_logClassSystem_id { get; set; }
    
        public virtual c_logClassSystem c_logClassSystem { get; set; }
    }
}
