//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_querySnapshots
    {
        public c_querySnapshots()
        {
            this.h_querySnapshots = new HashSet<h_querySnapshots>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public string C_user { get; set; }
        public string query { get; set; }
    
        public virtual ICollection<h_querySnapshots> h_querySnapshots { get; set; }
    }
}
