//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GADATAEntities : DbContext
    {
        public GADATAEntities()
            : base("name=GADATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<QUERYParameters> QUERYParameters { get; set; }
        public DbSet<QUERYS> QUERYS { get; set; }
        public DbSet<c_querySnapshots> c_querySnapshots { get; set; }
        public DbSet<l_querySnapshots> l_querySnapshots { get; set; }
        public DbSet<h_querySnapshots> h_querySnapshots { get; set; }
    }
}
