//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ia_Alert
    {
        public int id { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public string Type { get; set; }
        public string controller_name { get; set; }
        public Nullable<int> reference_id { get; set; }
        public string description { get; set; }
        public string Accept_user { get; set; }
        public Nullable<System.DateTime> Accept_timestamp { get; set; }
        public string Fix_user { get; set; }
        public Nullable<System.DateTime> Fix_timestamp { get; set; }
        public Nullable<System.DateTime> Detect_timestamp { get; set; }
        public string Close_user { get; set; }
        public Nullable<System.DateTime> Close_timestamp { get; set; }
        public string User_Comment { get; set; }
        public Nullable<int> controller_id { get; set; }
        public string controller_type { get; set; }
        public Nullable<int> AlertStatus { get; set; }
    }
}
