//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_dummyLogClassResult
    {
        public int id { get; set; }
        public string text { get; set; }
        public Nullable<int> c_logcClassRules_id { get; set; }
        public Nullable<int> c_Classification_id { get; set; }
        public Nullable<int> c_Subgroup_id { get; set; }
        public Nullable<int> code { get; set; }
    
        public virtual c_Classification c_Classification { get; set; }
        public virtual c_Subgroup c_Subgroup { get; set; }
    }
}
