//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_housekeeping
    {
        public int id { get; set; }
        public int c_housekeeping_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<int> nRowCountStart { get; set; }
        public Nullable<int> nRowCountEnd { get; set; }
        public Nullable<int> nLoopCount { get; set; }
        public Nullable<int> nDeleteCount { get; set; }
        public Nullable<int> nRunTime { get; set; }
        public int nJobID { get; set; }
    
        public virtual c_housekeeping c_housekeeping { get; set; }
    }
}
