//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_link
    {
        public int id { get; set; }
        public Nullable<int> L_pannel_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string iconcss { get; set; }
        public string icon { get; set; }
        public Nullable<int> Wiki_id { get; set; }
        public string url { get; set; }
        public string helptext { get; set; }
    
        public virtual L_pannel L_pannel { get; set; }
        public virtual Wiki Wiki { get; set; }
    }
}
