//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class l_querySnapshots
    {
        public int id { get; set; }
        public Nullable<int> snapshotId { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string htmlresult { get; set; }
    
        public virtual h_querySnapshots h_querySnapshots { get; set; }
    }
}
