//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipwearBeforeChange
    {
        public string controller_name { get; set; }
        public short Tool_Nr { get; set; }
        public System.DateTime TipchangeTimestamp { get; set; }
        public Nullable<double> FixedWearBeforeChange { get; set; }
        public Nullable<double> MoveWearBeforeChange { get; set; }
        public Nullable<double> WearBeforeChange { get; set; }
        public Nullable<int> WeldsBeforeChange { get; set; }
        public Nullable<short> DressBeforeChange { get; set; }
        public Nullable<double> C_FixedWearBeforeChange { get; set; }
        public Nullable<double> C_MoveWearBeforeChange { get; set; }
        public Nullable<double> ESTnSpotsFixedWearBefore100 { get; set; }
        public Nullable<double> ESTnSpotsMoveWearBefore100 { get; set; }
        public Nullable<int> TipAge_h_ { get; set; }
    }
}
