//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wiki
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Culture { get; set; }
        public string wiki1 { get; set; }
        public string searchtags { get; set; }
    }
}
