//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wiki
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Comments { get; set; }
        public System.DateTime createDate { get; set; }
        public int l_user_id { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<int> l_change_user_id { get; set; }
    }
}
