//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodytracking
    {
        public int id { get; set; }
        public string controller_name { get; set; }
        public Nullable<int> jobNo { get; set; }
        public Nullable<int> bodyNo { get; set; }
        public Nullable<System.DateTime> CycleStart { get; set; }
        public Nullable<System.DateTime> CycleEnd { get; set; }
        public Nullable<System.DateTime> ts_breakDownStart { get; set; }
        public Nullable<System.DateTime> ts_breakDownAck { get; set; }
        public Nullable<System.DateTime> ts_breakDownEnd { get; set; }
        public string FullLogtext { get; set; }
        public Nullable<int> refId { get; set; }
    }
}
