//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_alarm_ignore
    {
        public int id { get; set; }
        public Nullable<int> enable_bit { get; set; }
        public Nullable<int> error_number { get; set; }
        public Nullable<int> error_category { get; set; }
        public Nullable<int> error_number_mask { get; set; }
        public Nullable<int> error_category_mask { get; set; }
        public Nullable<int> C_operator { get; set; }
        public string Ignore { get; set; }
        public string UserComment { get; set; }
    }
}
