//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_controller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_controller()
        {
            this.rt_active_info = new HashSet<rt_active_info>();
        }
    
        public int id { get; set; }
        public string controller_name { get; set; }
        public Nullable<int> enable_bit { get; set; }
        public string systemId { get; set; }
        public string ip { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> flags { get; set; }
        public string LocationTree { get; set; }
        public string Assetnum { get; set; }
        public string ProductionTeam { get; set; }
        public string ResponsiblePloeg { get; set; }
        public string ClassificationTree { get; set; }
        public string CLassificationId { get; set; }
    
        public virtual c_controller_class c_controller_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rt_active_info> rt_active_info { get; set; }
    }
}
