//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_controller_class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_controller_class()
        {
            this.c_controller = new HashSet<c_controller>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool doConnect { get; set; }
        public int evStateChange { get; set; }
        public int evOperatingModeChange { get; set; }
        public int evConnectionChange { get; set; }
        public int evExecutionStatus { get; set; }
        public int evExecutionStatusTRob1 { get; set; }
        public int evBackupCompleted { get; set; }
        public int evDataResolveChange { get; set; }
        public int evExecutionCycleChange { get; set; }
        public int evTaskEnabledChange { get; set; }
        public int evMasterChange { get; set; }
        public int evMotionPointerTRob1Change { get; set; }
        public int evProgramPointerTRob1Change { get; set; }
        public int evMotionPointerTRob1ManualChange { get; set; }
        public int evProgramPointerTRob1ManualChange { get; set; }
        public int cVariableMask { get; set; }
        public int cVariableSearchMask { get; set; }
        public int cDeviceInfoMask { get; set; }
        public int cCSVLogMask { get; set; }
        public int cJobMask { get; set; }
        public int logCategoryMask { get; set; }
        public bool handleHSocket { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int setClock { get; set; }
        public int evLogMessageAction { get; set; }
        public int cPJVEventMask { get; set; }
        public int cPJVActionMask { get; set; }
        public int cErrorMask { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<c_controller> c_controller { get; set; }
    }
}
