//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_device_info
    {
        public int id { get; set; }
        public string name { get; set; }
        public int enable_bit { get; set; }
        public int poll_rate { get; set; }
        public int insert_update { get; set; }
        public string URL { get; set; }
    }
}
