//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_variable_search
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public c_variable_search()
        {
            this.rt_search_value = new HashSet<rt_search_value>();
        }
    
        public int id { get; set; }
        public string variable { get; set; }
        public int property { get; set; }
        public string datatype { get; set; }
        public int poll_rate { get; set; }
        public int enable_bit { get; set; }
        public int insert_update { get; set; }
        public string rt_table { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rt_search_value> rt_search_value { get; set; }
    }
}
