//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_variable
    {
        public int id { get; set; }
        public string variable { get; set; }
        public Nullable<int> poll_rate { get; set; }
        public Nullable<int> enable_bit { get; set; }
        public Nullable<int> event_enum { get; set; }
        public Nullable<int> sql_action { get; set; }
        public string rt_table { get; set; }
    }
}
