//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class h_alarm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public h_alarm()
        {
            this.rt_job_breakdown = new HashSet<rt_job_breakdown>();
        }
    
        public int id { get; set; }
        public Nullable<int> controller_id { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<System.DateTime> error_timestamp { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> L_error_id { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual c_controller c_controller { get; set; }
        public virtual L_error L_error { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rt_job_breakdown> rt_job_breakdown { get; set; }
    }
}
