//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_error
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public L_error()
        {
            this.h_alarm = new HashSet<h_alarm>();
        }
    
        public int C_id { get; set; }
        public Nullable<int> Number { get; set; }
        public string Title { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> l_description_id { get; set; }
        public Nullable<int> l_consequences_id { get; set; }
        public Nullable<int> l_causes_id { get; set; }
        public Nullable<int> l_actions_id { get; set; }
        public Nullable<int> l_type_id { get; set; }
        public Nullable<int> c_ClassificationId { get; set; }
        public Nullable<int> c_SubgroupId { get; set; }
        public Nullable<int> c_RuleId { get; set; }
        public string CleanTitle { get; set; }
        public Nullable<bool> ClassCalculated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<h_alarm> h_alarm { get; set; }
        public virtual L_actions L_actions { get; set; }
        public virtual L_causes L_causes { get; set; }
        public virtual L_consequences L_consequences { get; set; }
        public virtual L_description L_description { get; set; }
        public virtual L_type L_type { get; set; }
    }
}
