//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_active_info
    {
        public int id { get; set; }
        public Nullable<int> c_controller_id { get; set; }
        public Nullable<int> h_alarm_id { get; set; }
        public Nullable<int> rt_alarm_id { get; set; }
        public Nullable<int> rt_job_id { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<int> program_number { get; set; }
        public Nullable<int> body_number { get; set; }
        public Nullable<int> application_error { get; set; }
        public Nullable<int> operating_mode { get; set; }
        public Nullable<int> execution_status { get; set; }
        public Nullable<int> controller_state { get; set; }
        public Nullable<int> master_state { get; set; }
        public Nullable<int> at_home { get; set; }
        public Nullable<int> vasc_state { get; set; }
        public Nullable<int> task_execution_status { get; set; }
        public Nullable<System.DateTime> ts_breakDownAck { get; set; }
        public Nullable<System.DateTime> ts_breakDownStart { get; set; }
        public string vasc_session { get; set; }
        public Nullable<int> part_data_count { get; set; }
    
        public virtual c_controller c_controller { get; set; }
    }
}
