//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EqUiWebUi.Areas.VASC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rt_job()
        {
            this.rt_job_breakdown = new HashSet<rt_job_breakdown>();
        }
    
        public int id { get; set; }
        public Nullable<int> c_controller_id { get; set; }
        public Nullable<int> c_job_id { get; set; }
        public Nullable<int> jobNo { get; set; }
        public Nullable<int> bodyNo { get; set; }
        public Nullable<System.DateTime> ts_Start { get; set; }
        public Nullable<System.DateTime> ts_End { get; set; }
        public Nullable<int> errorMask { get; set; }
        public Nullable<int> breakDownCount { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> ts_breakDownStart { get; set; }
        public Nullable<System.DateTime> ts_breakDownEnd { get; set; }
        public Nullable<System.DateTime> ts_breakDownAck { get; set; }
        public Nullable<System.DateTime> C_timestamp { get; set; }
        public Nullable<double> cycletime { get; set; }
    
        public virtual c_controller c_controller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rt_job_breakdown> rt_job_breakdown { get; set; }
        public virtual c_job c_job { get; set; }
    }
}
